// Generated by CoffeeScript 1.3.3
(function() {
  var main_vm;

  main_vm = function() {
    this.title = ko.observable("Hello");
  };

  $(document).one('app_init', function(e, d) {
    console.log("Loading Main VM");
    ko.applyBindings(new main_vm());
  });

}).call(this);
